StartupEvents.registry('fluid', e =>{
    e.create('liquid_infinity')
    .thinTexture(0x361d50)
    .bucketColor(0x361d50)
    .displayName("Liquid Infinity")
    e.create('liquid_dragons_breath')
    .thinTexture(0x7e2f7e)
    .bucketColor(0x7e2f7e)
    .displayName("Liquid Dragon's Breath")
    e.create('glowing_liquid')
    .thickTexture(0xc7bd32)
    .bucketColor(0xc7bd32)
    .displayName("Glowing Liquid")
    e.create('liquid_sun')
    .thickTexture(0x9b5514)
    e.create('fungal_mixture')
    .thickTexture(0x3b2f3f)
    e.create('liquid_antimatter')
    .thinTexture(0xb31eb3)
    .rarity('epic')
    e.create('liquid_polonium')
    .thinTexture(0x245c45)
})

Color.of("#361d50")
Color.of('#b31eb3')
Color.of('#c7bd32')
Color.of('#9b5514')
Color.of("#245c45")