StartupEvents.registry('fluid', e => {
    e.create('liquid_infinity')
      .thinTexture(0x361d50)
      .bucketColor(0x361d50)
      .displayName("Liquid Infinity")
    e.create('liquid_dragons_breath')
      .thinTexture(0x7e2f7e)
      .bucketColor(0x7e2f7e)
      .displayName("Liquid Dragon's Breath")
    e.create('glowing_liquid')
      .thickTexture(0xf8ffab)
      .bucketColor(0xf8ffab)
      .displayName("Glowing Liquid")
    e.create('liquid_sun')
      .thickTexture(0x9b5514)
    e.create('fungal_mixture')
      .thickTexture(0x3b2f3f)
    e.create('liquid_antimatter')
      .thinTexture(0xb31eb3)
      .rarity('epic')
      .tag('toastech:liquid_antimatter')
    e.create('liquid_polonium')
      .thinTexture(0x245c45)
      .tag('toastech:liquid_polonium')
    e.create('pulsating_liquid')
      .thinTexture(0x56ac68)
      .tag('toastech:pulsating_liquid')
    e.create('vibrant_liquid')
      .thinTexture(0xe0ea6a)
      .tag('toastech:vibrant_liquid')
    e.create('liquid_void')
      .thickTexture(0x000001)
    e.create('magical_water')
      .thinTexture(0x1c0938)
})

Color.of("#361d50")
Color.of('#b31eb3')
Color.of('#f8ffab')
Color.of('#9b5514')
Color.of("#245c45")