JEIEvents.hideItems(event => {
  event.hide('extendedcrafting:redstone_ingot')
  event.hide('extendedcrafting:redstone_nugget')
  event.hide('extendedcrafting:redstone_ingot_block')
  event.hide([
    '#enderio:clear_glass_p', 
    '#enderio:clear_glass_np', 
    '#enderio:clear_glass_m', 
    '#enderio:clear_glass_nm', 
    '#enderio:clear_glass_a', 
    '#enderio:clear_glass_na',
    '#enderio:clear_glass_d', 
    '#enderio:clear_glass_dp', 
    '#enderio:clear_glass_dnp', 
    '#enderio:clear_glass_dm', 
    '#enderio:clear_glass_dnm', 
    '#enderio:clear_glass_da', 
    '#enderio:clear_glass_dna',
    '#enderio:clear_glass_e', 
    '#enderio:clear_glass_ep', 
    '#enderio:clear_glass_enp', 
    '#enderio:clear_glass_em', 
    '#enderio:clear_glass_enm', 
    '#enderio:clear_glass_ea', 
    '#enderio:clear_glass_ena',
    '#enderio:fused_quartz_e', 
    '#enderio:fused_quartz_ep', 
    '#enderio:fused_quartz_enp', 
    '#enderio:fused_quartz_em', 
    '#enderio:fused_quartz_enm', 
    '#enderio:fused_quartz_ea', 
    '#enderio:fused_quartz_ena', 
    '#enderio:fused_quartz_d', 
    '#enderio:fused_quartz_dp', 
    '#enderio:fused_quartz_dnp', 
    '#enderio:fused_quartz_dm', 
    '#enderio:fused_quartz_dnm', 
    '#enderio:fused_quartz_da', 
    '#enderio:fused_quartz_dna',
    '#enderio:fused_quartz', 
    '#enderio:fused_quartz_p', 
    '#enderio:fused_quartz_np', 
    '#enderio:fused_quartz_m', 
    '#enderio:fused_quartz_nm', 
    '#enderio:fused_quartz_a', 
    '#enderio:fused_quartz_na'
  ])
  event.hide('ae2:facade')
  const removedItems = Utils.server.persistentData.removedItems
  removedItems.forEach(item => {
    event.hide(item)
  })
})

JEIEvents.addItems(event => {
  event.add('extendedcrafting:ultimate_singularity')
  event.add("craftingstation:crafting_station_slab")
  event.add("craftingstation:crafting_station")
  event.add([
    'enderio:clear_glass_e', 
    'enderio:clear_glass_ep', 
    'enderio:clear_glass_enp', 
    'enderio:clear_glass_em', 
    'enderio:clear_glass_enm', 
    'enderio:clear_glass_ea', 
    'enderio:clear_glass_ena', 
    'enderio:clear_glass_d', 
    'enderio:clear_glass_dp', 
    'enderio:clear_glass_dnp', 
    'enderio:clear_glass_dm', 
    'enderio:clear_glass_dnm', 
    'enderio:clear_glass_da', 
    'enderio:clear_glass_dna',
    'enderio:clear_glass', 
    'enderio:clear_glass_p', 
    'enderio:clear_glass_np', 
    'enderio:clear_glass_m', 
    'enderio:clear_glass_nm', 
    'enderio:clear_glass_a', 
    'enderio:clear_glass_na',
    'enderio:fused_quartz_e',
    'enderio:fused_quartz_ep',
    'enderio:fused_quartz_enp',
    'enderio:fused_quartz_em',
    'enderio:fused_quartz_enm',
    'enderio:fused_quartz_ea',
    'enderio:fused_quartz_ena',
    'enderio:fused_quartz_d',
    'enderio:fused_quartz_dp',
    'enderio:fused_quartz_dnp',
    'enderio:fused_quartz_dm',
    'enderio:fused_quartz_dnm',
    'enderio:fused_quartz_da',
    'enderio:fused_quartz_dna',
    'enderio:fused_quartz',
    'enderio:fused_quartz_p',
    'enderio:fused_quartz_np',
    'enderio:fused_quartz_m',
    'enderio:fused_quartz_nm',
    'enderio:fused_quartz_a',
    'enderio:fused_quartz_na'
  ])
  event.add(Item.of('ae2:facade', '{item:"avaritia:infinity"}'))
})